const banks = [
  { id: 1, name: "Access Bank", code: "044", shortName: "Access" },
  { id: 2, name: "Citibank", code: "023", shortName: "Citi" },
  { id: 3, name: "Ecobank", code: "050", shortName: "Ecobank" },
  { id: 4, name: "Fidelity Bank", code: "070", shortName: "Fidelity" },
  { id: 5, name: "First Bank", code: "011", shortName: "First" },
  { id: 6, name: "FCMB", code: "214", shortName: "FCMB" },
  { id: 7, name: "Globus Bank", code: "00103", shortName: "Globus" },
  { id: 8, name: "GTBank", code: "058", shortName: "GTB" },
  { id: 9, name: "Heritage Bank", code: "030", shortName: "Heritage" },
  { id: 10, name: "Jaiz Bank", code: "301", shortName: "Jaiz" },
  { id: 11, name: "Keystone Bank", code: "082", shortName: "Keystone" },
  { id: 12, name: "Kuda Bank", code: "50211", shortName: "Kuda" },
  { id: 13, name: "Moniepoint", code: "50515", shortName: "Moniepoint" },
  { id: 14, name: "Opay", code: "999992", shortName: "Opay" },
  { id: 15, name: "Palmpay", code: "999991", shortName: "Palmpay" },
  { id: 16, name: "Parallex Bank", code: "526", shortName: "Parallex" },
  { id: 17, name: "Polaris Bank", code: "076", shortName: "Polaris" },
  { id: 18, name: "Premium Trust Bank", code: "105", shortName: "Premium" },
  { id: 19, name: "Providus Bank", code: "101", shortName: "Providus" },
  { id: 20, name: "Stanbic IBTC", code: "221", shortName: "Stanbic" },
  { id: 21, name: "Sterling Bank", code: "232", shortName: "Sterling" },
  { id: 22, name: "UBA", code: "033", shortName: "UBA" },
  { id: 23, name: "Union Bank", code: "032", shortName: "Union" },
  { id: 24, name: "Unity Bank", code: "215", shortName: "Unity" },
  { id: 25, name: "Wema Bank", code: "035", shortName: "Wema" },
  { id: 26, name: "Zenith Bank", code: "057", shortName: "Zenith" },
];

export default banks;
